project '../BlackJackBuddy.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'BlackjackBuddy' do
    pod 'SnapKit'
    pod 'SwiftFormat/CLI'
end
